baseURL = 'https://pandaqi.com/tutorials'
languageCode = 'en-us'
title = 'Pandaqi Tutorials'
description = 'Tutorials about anything and everything'
author = "Pandaqi"
theme = 'pandaqi-tutorials'
summaryLength 	= 18

pygmentsUseClasses = true
pygmentsCodefences = true

sectionPagesMenu = "main"

[pagination]
  pagerSize = 10

[build]
  noJSConfigInAssets = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2

    [markup.goldmark.renderer] 
        unsafe = true

    [ markup.goldmark.extensions]
        table = true

[params]
    testOnlyCriticalStyle = false
    loadPQToolsAsSeparateFiles = false

[markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4
    noClasses = false
